### ISSUE TITLE
ID is marked as REQUIRED in the Swagger UI on all endpoints.

### ISSUE THREAD

**Issue by Crystalzord** [servicecatalog/oscm-rest-api#106]
**Summary**
ID is not necessary  in some endpoints (GET for all resources), and required in others (where ID is a Path Parameter). This is difficult to manage since there is no annotation for this (AFAIK). In this situation we will have to modify the final json/yaml manually after it is generated.

**Acceptance criteria**
ID is marked as required only when it is present in the URI as the Path Parameter.

**Additional context**
- Maybe a solution would be to create a custom annotation basing on Swagger's one.
- ![obraz](https://user-images.githubusercontent.com/47355402/67463282-6c317b00-f641-11e9-90a6-10d6ed4edf16.png)

**Comment by adamczykba** [comment]
Due to possible conflict and redundancies with #170, fix for this bug will be implemented in scope of #170
