### ISSUE TITLE
Authentication with OIDC

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-rest-api#109]
**Summary and Business Motivation**
Important REST endpoints shall be enabled to use token based authentication with Open ID Connect.

**Details**
To be done

**Acceptance criteria**
To be done

**Additional context**
This is connected with the identity service. See https://github.com/servicecatalog/oscm/issues/302.

**Comment by kowalczyka** [comment]
Closing as OIDC mode support issue has already been resolved
