### ISSUE TITLE
[Account] Improve error handling

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-rest-api#117]
**Summary**
Right now, error messages that are delivered though API request are not meaningful at all. 
We should review them and make it so end user actually knows what went wrong.

**Details**
N/A

**Acceptance criteria**
- [ ] error handling is reviewed
- [ ] error messages are more meningfull (no generic error messages!)
- [ ] proper error codes are used - 4xx for internal errors, 5xx for external errors
- [ ] APIs that were refactored earlier (Event, Marketplace) should be adapted to new way of handling exceptions 

**Additional context**
Instead of rethrowing exception, let's try [following approach](https://dennis-xlc.gitbooks.io/restful-java-with-jax-rs-2-0-en/cn/part1/chapter7/exception_handling.html
)

**Comment by kowalczyka** [comment]
Closing as it will be handled within #219
