### ISSUE TITLE
[Marketplace] Improve error handling

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-rest-api#120]
**Summary**
Right now, error messages that are delivered though API request are not meaningful at all. 
We should review them and make it so end user actually knows what went wrong.

**Details**
N/A

**Acceptance criteria**
- [x] error handling is reviewed
- [x] error messages are more meningfull (no generic error messages!)
- [x] proper error codes are used - 4xx for internal errors, 5xx for external errors

**Additional context**
N/A

**Comment by adamczykba** [comment]
Error returned by this API are not informative enough as the response consists only of the stracktrace
![obraz](https://user-images.githubusercontent.com/47355402/67601832-9a17dc00-f775-11e9-87ed-688bbd8c3006.png)

**Comment by kowalczyka** [comment]
Closing as it will be handled within #219
