### ISSUE TITLE
[Operation] Improve error handling

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-rest-api#121]
**Summary**
Right now, error messages that are delivered though API request are not meaningful at all. 
We should review them and make it so end user actually knows what went wrong.

**Details**
N/A

**Acceptance criteria**
- [ ] error handling is reviewed
- [ ] error messages are more meningfull (no generic error messages!)
- [ ] proper error codes are used - 4xx for internal errors, 5xx for external errors

**Additional context**
N/A

**Comment by GoebelL** [comment]
> 4xx for internal errors, 5xx for external errors
Should be rather the other way around. "4xx" codes are client errors and "5xx" are server errors.

**Comment by adamczykba** [comment]
@GoebelL 
To be more specific, what I meant is to use 4xx codes for errors caused inside of *oscm-rest* and 5xx's for errors coming from oscm-core. It works in simillar way right now, however errors are to generic and hardly informative enough

**Comment by kowalczyka** [comment]
Closing as it will be handled within #219
