### ISSUE TITLE
POST/PUT endpoints should require ID of dependent entity instead of whole represenation

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-rest-api#134]
**Summary**
POST/PUT endpoint should require only ID of related entities instead of whole JSON entity representation.

**Details**
N/A

**Acceptance criteria**
- [ ] places where whole represenation is required are properly identified and documented in respective issues
- [ ] this issue is converted into epic and module-specific tasks are created (due to complexity)
- [ ] requirement of JSON entity representation is replaced with id (where applicable)
- [ ] overall code coverage is at least 80%

**Additional context**
- if needed - this issue should be raised to the epic
- sample occurence: Services#POST 
![obraz](https://user-images.githubusercontent.com/47355402/62462844-bfa1d480-b788-11e9-87b8-16e3de29df31.png)

**Comment by kowalczyka** [comment]
Closing as the task is partially done and separate tasks are defined: #237 #238
