### ISSUE TITLE
Implement unit tests for Event API

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-rest-api#15]
Unit tests have to be implemented for *oscm-rest-api-event* submodule.

**Details**
N/A

**Acceptance criteria**
- [ ] overall code coverage is at least 60%

*Unit tests for following submodules are implemented:*
- [ ] oscm-rest-api-event

**Additional context:**
N/A

**Comment by Crystalzord** [comment]
Done in pull request: https://github.com/servicecatalog/oscm-rest-api/pull/62
