### ISSUE TITLE
Organization#POST execution doesn't work in Swagger

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-rest-api#157]
**Describe the bug**

**To Reproduce**
1. Login to swagger-ui
2. Authenticate as admin
3. Fill in required params in organization#POST section
4. Try to execute sample POST request

**Expected behavior**
Request passes without any exception

**Observed behavior**
Executing the request results with error 500 - Unauthorized Access by Principal Denied

**Screenshots**
![obraz](https://user-images.githubusercontent.com/47355402/67473117-6d1ed880-f652-11e9-9636-4291d81edbf7.png)
![obraz](https://user-images.githubusercontent.com/47355402/67473170-8031a880-f652-11e9-8d04-98958abd5d2b.png)

**Additional context**
- the possible reason for this behaviour may be misconfigured web.xml

**Comment by kowalczyka** [comment]
Closing as the endpoint is updated and verified as working. Please check #205
