### ISSUE TITLE
Values not passed properly while executing UserRoles#PUT with swagger

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-rest-api#161]
**Describe the bug**
Instead of userId provided in endpoint params in Swagger UI, '0' is used.

**To Reproduce**
1. Authenticate to swagger-ui as administrator
2. Execute UserRoles#PUT

**Expected behavior**
Request should pass without any error

**Observed behavior**
Error of Could not find object of type 'USER' with business key '0'" is returned

**Screenshots**
![obraz](https://user-images.githubusercontent.com/47355402/67600396-5ec7de00-f772-11e9-8103-4124f87c84a7.png)
![obraz](https://user-images.githubusercontent.com/47355402/67600427-6be4cd00-f772-11e9-9342-f1e8f146d3e8.png)
![obraz](https://user-images.githubusercontent.com/47355402/67601088-d34f4c80-f773-11e9-8d36-fe779c0ab754.png)

**Additional context**
N/A

**Comment by GoebelL** [comment]
If you put userId in path, check also for currect encoding.

**Comment by Crystalzord** [comment]
Closed in https://github.com/servicecatalog/oscm-rest-api/pull/178
