### ISSUE TITLE
Values not passed properly while executing Users#PUT with swagger

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-rest-api#162]
**Describe the bug**
Instead of userId provided in endpoint params in Swagger UI, '0' is used.

**To Reproduce**
1. Authenticate to swagger-ui as administrator
2. Execute User#PUT

**Expected behavior**
Request should pass without any error

**Observed behavior**
Error of Could not find object of type 'USER' with business key '0'" is returned

**Screenshots**
![obraz](https://user-images.githubusercontent.com/47355402/67600992-91260b00-f773-11e9-93f4-10ab09b4954c.png)
![obraz](https://user-images.githubusercontent.com/47355402/67601017-a307ae00-f773-11e9-8558-5e9403444c84.png)

**Additional context**
N/A

**Comment by Crystalzord** [comment]
Closed in https://github.com/servicecatalog/oscm-rest-api/pull/178
