### ISSUE TITLE
Unable to execute UsageLicenses#GET via Swagger UI

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-rest-api#165]
**Describe the bug**
Attempt of excecuting UsageLicenses#GET results in error being thrown

**To Reproduce**
1. Authenticate to swagger-ui as administrator
2. Execute UsageLicenses#GET

**Expected behavior**
Request should pass without any error

**Observed behavior**
Error page (not JSON) is returned

**Screenshots**
![obraz](https://user-images.githubusercontent.com/47355402/67603773-17dde680-f77a-11e9-9a09-68f494ef939b.png)

**Additional context**
N/A

**Comment by Crystalzord** [comment]
Fixed in pull/175
