### ISSUE TITLE
licKey params in UsageLicenses endpoints are not marked as required despite of their presence in URL

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-rest-api#166]
**Describe the bug**
UsageLicenses#PUT and UsageLicenses#DELETE endpoints uses *licKey* param that is present into request URL (and therefore is mandatory) which is not marked as required.

**To Reproduce**
1. Authenticate to Swagger UI
2. Scroll down tu UsageLicenses section
3. Unfold PUT and DELETE edpoint descriptions

**Expected behavior**
licKey param is marked as required in both of the endpoints

**Observed behavior**
licKey param is not marked as required in both of the endpoints

**Screenshots**
![obraz](https://user-images.githubusercontent.com/47355402/67604204-44dec900-f77b-11e9-83bb-f543b3738a76.png)
![obraz](https://user-images.githubusercontent.com/47355402/67604233-59bb5c80-f77b-11e9-9354-0fde0e60e9dc.png)

**Additional context**
N/A

**Comment by Crystalzord** [comment]
Fix merged to master
