### ISSUE TITLE
[Swagger] PathParams are marked as REQUIRED in the endpoints that doesn't use them

### ISSUE THREAD

**Issue by Crystalzord** [servicecatalog/oscm-rest-api#170]
**Summary:**
PathParams like LicKey or ID are not necessary in some endpoints (GET for all resources or POST), and required in others (where LicKey or ID is a Path Parameter). 
To straighten this up, let's introduce some generic solution that will allow developers to add further PathParams freely, without being concerned about inconsistencies in the Swagger documentation. 

**Acceptance criteria:**
- [x] PathParams like Id and LicKey are no longer marked as required in the endpoints that doesn't use them
- [x] proposed solution is extendable - if we want to introduce further path params, there will be no issue with them being required

**Additional context:**
- This issue is similar to https://github.com/servicecatalog/oscm-rest-api/issues/106
- Implementing a decorator pattern/some other pattern could be a good call there

**Comment by adamczykba** [comment]
Maybe we should implement some kind of builder? Find a way to 'build' request params class independently for each endpoint, which will define if it needs any of the pathparams (wether it be id, userid or lickey)

**Comment by kowalczyka** [comment]
This task will be done within https://github.com/servicecatalog/oscm-rest-api/issues/194
