### ISSUE TITLE
Fix permissions to REST endpoints

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-rest-api#174]
**Describe the bug**
After one of recent changes it seems that something went wrong with user permissions when it comes to REST endpoints.
Taking for example Settings#POST endpoint - *administrator* is not able to do anything there and is greeted with *401 - Unauthorized*. This definitely need to be fixed.

**To Reproduce**
1. Send POST request to create a new Setting (authenticate as admin - 1000)
2. See the *401 - Unauthorized* error page in response

**Expected behavior**
Users with the proper roles should be able to execute the REST endpoints

**Observed behavior**
User with high privileges like *administator* is not able to create new Settings

**Screenshots**
![obraz](https://user-images.githubusercontent.com/47355402/69521871-4957f680-0f60-11ea-98ca-7f0ea109d45a.png)

**Additional context**
- it is possible that this bug is somewhat related to web.xmls being join with *maven-cargo* plugin

**Comment by Crystalzord** [comment]
Closing as not relevant
