### ISSUE TITLE
Implement unit tests for Service API

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-rest-api#18]
Unit tests have to be implemented for *oscm-rest-api-service* submodule.

**Details**
N/A

**Acceptance criteria**
- [ ] overall code coverage is at least 60%

*Unit tests for following submodules are implemented:*
- [ ] oscm-rest-api-service

**Additional context:**
N/A

**Comment by adamczykba** [comment]
@Crystalzord 
Is this task done?

**Comment by Crystalzord** [comment]
Yes, closing.
