### ISSUE TITLE
GET list endpoints require ids

### ISSUE THREAD

**Issue by cworf91** [servicecatalog/oscm-rest-api#188]
Describe the bug
For the get endpoints of:

- Settings
- Services
- TechnicalServices 

The endpoints does provide a list for existing services. Nevertheless, the id is mandetory. It doesn´t matter which id is provided, the result ist the same list of results

Details
The get endpoints are supposed to serve a list of existing services in the current organization without providing a id

To Reproduce

    Invoke <BASEURL>/oscm-rest-api/#/users and login with user key 10000
    Click 'GET' and 'Try Out'
    See the field 'serviceId'

Expected behavior
'id' is optional and when omitted execute leads to returning a list.

Observed behavior
'id' is mandatory and can't be omitted for execution.

**Comment by kowalczyka** [comment]
This task will be done within https://github.com/servicecatalog/oscm-rest-api/issues/194
