### ISSUE TITLE
Swagger misleading documentation

### ISSUE THREAD

**Issue by mchudy-fujitsu** [servicecatalog/oscm-rest-api#189]
**Describe the bug**
The following endpoints having wrong or misleading documentation
* GET /{version}/organizations - Path variable id is unnecessary
* GET/{version}/paymentinfos - Path variable id is unnecessary
* POST /{version}/events - Path variable id is unnecessary
* POST /{version}/onbehalfusers - Path variables id and userId are unnecessary
* DELETE /{version}/onbehalfusers - Path variables id and userId are unnecessary
* GET /{version}/users/{userId}/userroles - Path variable id is unnecessary
* PUT /{version}/users/{userId}/userroles - Path variable id is unnecessary
* GET /{version}/marketplaces - Path variable id is unnecessary
* POST /{version}/marketplaces - Path variable id is unnecessary
* PUT /{version}/marketplaces/{id}/entries/{sKey} - sKey is listed as query param not as path variable
* GET /{version}/settings - Path variable id is unnecessary
* GET /{version}/services/{id}/pricemodel/customer/{orgKey} - orgKey is listed as query param not as path variable 
* PUT /{version}/services/{id}/pricemodel/customer/{orgKey} - orgKey is listed as query param not as path variable 
* DELETE /{version}/technicalservices/{id}/suppliers/{orgId} - orgId is listed as query param not as path variable 
* POST /{version}/subscriptions/{id}/usagelicenses - Path variable licKey is unnecessary 
* GET /{version}/subscriptions/{id}/usagelicenses - vath Variable licKey is unnecessary
* GET /{version}/subscriptions/{id} - Path variable licKey is unnecessary
* PUT /{version}/subscriptions/{id} - Path variable licKey is unnecessary
* DELETE /{version}/subscriptions/{id} - Path variable licKey is unnecessary
* GET /{version}/subscriptions/ - Path variables licKey and id are unnecessary
* PUT /{version}/subscriptions/ - Path variables licKey and id are unnecessary

**To Reproduce**
1. Go to 'oscm-rest-api/#/.'
2. Check the given endpoint.
3. Swagger requires unnecessary param/variable which has no effect on the returned outcome.

**Expected behavior**
Swagger doesn't require unnecessary params/variables.

**Comment by kowalczyka** [comment]
This bug will be resolved in the scope of #194.
