### ISSUE TITLE
Import of technical service templates

### ISSUE THREAD

**Issue by cworf91** [servicecatalog/oscm-rest-api#190]
**Summary**
Although it is possible to create a technical service via the rest api, an import is not yet possible. Therefore it should be possible to import a technical service in XML format via the rest API. 

**Details**
The rest endpoint "/technicalservices" already exist in OSCM so far, but it don´t allow the import of a technical service yet. Therefore, the existing endpoint should be extended to import a technical service in XML format. 
For this endpoint Swagger ui documentation must also be updated.

**Acceptance criteria**
[ ] Technical service import endpoint is created
[ ] Endpoint is Swagger ui documented
[ ] Endpoint is Tested

**Comment by GoebelL** [comment]
According the REST design the endpoints correspond to the resource representations. Therefore an URI like "/oscm-rest-api/v1/technicalservices" is where users expect such XML template import.
 
According this feature request, the existing endpoint POST method (and backend?)  should be extended to take possible XML data from the request body for import.
