### ISSUE TITLE
[Entrys Endpoint] for Publish Service

### ISSUE THREAD

**Issue by cworf91** [servicecatalog/oscm-rest-api#192]
**Summary**
So far it is possible to create a service via rest api, but it is not yet possible to publish this service on a marketplace. Therefore, a new endpoint should be created, which enables the function to publish a service on a marketplace.

**Details**
Publishing a service on a marketplace is an essential function, therefore an endpoint must be created for this funcitonality. It must be possible to publish a certain service (serviceId) on a certain marketplace (mpId).

**Acceptance criteria**
[ ] Existing service can be published on a Marketplace
[ ] The published service can be subscribed by a customer
[ ] The service was published on the correct marketplace in the correct organization
[ ] The endpoint was tested
[ ] Endpoint is Swagger ui documented

**Comment by GoebelL** [comment]
There is a rest representation of catalogue entries. Scrolling down in the Swagger UI you find this:
![image](https://user-images.githubusercontent.com/14805690/76876243-efae6b80-6871-11ea-826f-f45872b366b6.png)

I guess there is also a way to post them, but I don't know by with endpoint.

**Comment by GoebelL** [comment]
But yes of course - it would be nicer to have a dedicated endpoint here. As the API is representational resource oriented, I'd suggest the respective endpoint name to be "/entries". 
@cworf91 
Ok to rename this?

**Comment by cworf91** [comment]
@cworf91 Yes

**Comment by cworf91** [comment]
With the put endpoint /{version}/marketplaces/{id}/entry/{sKey}, a service can now be published on a marketplace. Therefore some corrections have been made, e.g. B. "sKey" is now a path parameter and not a query parameter.

To publish a service, you need the service key (database key) and the marketplace ID. When you call the endpoint to publish a service, use the following body:

{
"anonymVisible": true,
"visibleInCatalog": true,
"Floor": 1
}

In other cases, adjust the body.
To activate the published service, the put endpoint /{version}/services/{id}/status must also be called.
