### ISSUE TITLE
[Swagger UI] subscriptions endpoint requires a usage license key

### ISSUE THREAD

**Issue by cworf91** [servicecatalog/oscm-rest-api#193]
**Describe the bug**
The Swagger UI requires a license key for some rest endpoints even if they are not necessary. E.g
- subscriptions
 
**To Reproduce**
1. Go to swagger ui
2. Click on subscriptions
3. See required license key

**Expected behavior**
The endpoint should be work without a license key. The license key is an optional attribute.

**Comment by kowalczyka** [comment]
The issue has been fixed within https://github.com/servicecatalog/oscm-rest-api/pull/213
