### ISSUE TITLE
[Swagger UI] Improve documentation

### ISSUE THREAD

**Issue by cworf91** [servicecatalog/oscm-rest-api#194]
**Summary**
Swagger UI provides a documentation for the rest API. In many places, however, the documentation is meaningless.  Nevertheless, the documentation should provide a meaningfull description of the endpoints. 

**Details**
The current state of swagger UI looks like a default documentation for a rest api. For instance: 
Get /{version}/subscriptions requires a ID, which is useless. The endpoint will work with every given id. Nevertheless, in some endpoints the id is neccessary indeed. But it´s difficult to figure out which id should be provided, because the description is for every endpoint the same: "ID of a single resource". This should be customized to a more meaningfull description for all endpoints like: "To get a certain subscription, provide a subscription id". 

Furthermore a version is also required. If the version is incorrect or missing, a 404 response code is returned. This should be also improved to get a more intuitiv handling for the swagger ui. 

**Acceptance criteria**
- remove all unnecessary parameters (e.g. id)
- provide meaningfull description for endpoints operation, parameters etc.
- provide the default value (v1) for api version in documentation

Following rest resources related endpoints should be validated against mentioned criteria and updated if necessary:
- [x] /billingcontacts - DONE [PR](https://github.com/servicecatalog/oscm-rest-api/pull/206)- @kowalczyka 
- [x] /organizations - DONE [PR](https://github.com/servicecatalog/oscm-rest-api/pull/205) - @kowalczyka 
- [x] /paymentinfos - DONE [PR](https://github.com/servicecatalog/oscm-rest-api/pull/207) - @kowalczyka 
- [x] /onbehalfusers - DONE [PR](https://github.com/servicecatalog/oscm-rest-api/pull/214) - @cworf91 
- [x] /roles - DONE [PR](https://github.com/servicecatalog/oscm-rest-api/pull/208) - @kowalczyka
- [x] /users - DONE [PR](https://github.com/servicecatalog/oscm-rest-api/pull/187) - @mchudy-fujitsu 
- [x] /marketplaces - DONE [PR](https://github.com/servicecatalog/oscm-rest-api/pull/210) - @kowalczyka
- [x] /settings - DONE [PR](https://github.com/servicecatalog/oscm-rest-api/pull/211) - @kowalczyka
- [x] /services - DONE [PR](https://github.com/servicecatalog/oscm-rest-api/pull/217) - @kowalczyka
- [x] /subscriptions - DONE [PR](https://github.com/servicecatalog/oscm-rest-api/pull/213)- @KabacinskiPiotr
- [x] /usagelicenses - DONE [PR](https://github.com/servicecatalog/oscm-rest-api/pull/212) - @cworf91

**Comment by GoebelL** [comment]
Related https://github.com/servicecatalog/oscm-rest-api/issues/189

**Comment by GoebelL** [comment]
@cworf91 
This FR description needs some clearing. Please define with a few **acceptance criteria** in exact words what is expected. Add theses criteria section in the description above.
