### ISSUE TITLE
Enhance /service endpoint to query tags and reviews 

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-rest-api#198]
**Summary**
For UI based integration the visual data of existing services shall be accessible via the Rest API. 
 
**Details**
Although the tag and review information is depicted in the example response of the Swagger UI documentation it is in fact missing in the JSON response. There is obviously no way to query said information. 
The request is to extend the representational data and service endpoint to provide
* All tags defined for given service (as shown in this example)
* Number of reviews and rating stars (as shown in this example)

**Acceptance criteria**
- [ ] All tags are included in representational JSON response
- [ ] Review data is included
  
**Additional context**
NA

**Comment by GoebelL** [comment]
Move image data to a separate feature request issue.

**Comment by sokichi-fj** [comment]
@GoebelL Embedding image will make response slower if the image is large. Also cache will not work well. I think we can use the url of image to keep the respons small.

**Comment by GoebelL** [comment]
@sokichi-fj 
Indeed the image icon is a bit tricky thing. Therefore I have extracted this part into a separate feature request: #201.
Currently the image itself is not accessible via URL. We will think about an extension in the oscm core to provide the image from URL.

**Comment by sokichi-fj** [comment]
@GoebelL We confiremd to fetch tags and review score via `/services` endpoint. In addition to GET, do you have a plan to support POST/PUT/DELETE for tag and review? Or are these methods already supported?
