### ISSUE TITLE
Provide Readme

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-rest-api#2]
Provide for description in this repository readme on how to deploy the API with latest OSCM. 

**Summary**
I think it would be a good idea to write a few lines of documentation in the README file.

**Acceptance criteria**
Readme is informing about simple details, such as where it is deployed or how to access Swagger UI after it is merged to master.

**Additional context**
I think it should be done after merging swagger branch to master.

**Comment by Crystalzord** [comment]
Done and merged to master branch
