### ISSUE TITLE
Provide for searching services

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-rest-api#200]
**Summary**
OSCM provides a full text search for marketable services and subscriptions. In case of long list scenarios with many entries this function offers the most efficient way to query particular services from a user's POV. The request is to make OSCM marketable service search available via Rest API.
   
**Details**
The right interface endpoint has to be elaborated. IMHO a good and reasonable cheap solution could be to extend the /service GET method with an optional URL parameter for the search query. If provided the endpoint implementation delegates the input to the search service. The parameter value may represent the search query like the user input in the search field located in the header of the marketplace portal.

**Acceptance criteria**
- [ ] Services can be searched same as via UI
- [ ] Length of search result list is fix limited (currently limited to 100 by the search service)

**Additional context**
Add any other context or screenshots about the task.

**Comment by sokichi-fj** [comment]
@GoebelL We would like to configure  

1. query
2. count per page (limit)
3. page number

from client of the APIs by using query string or similar method.

**Comment by GoebelL** [comment]
The information of 2.+3. is not available and cannot be provided here. The search result list is unpaged. It is limited by length. However you can use exact, partial or close matching query strings to locate services. It's using full text search with stemming in names, description and parameters. If required you can find every service by narrowing the search query.

**Comment by sokichi-fj** [comment]
@GoebelL Thanks. Does OSCM has default number for the length of list? Or can developer or user set the length?
