### ISSUE TITLE
Remove unneeded parameters for GET /organizations

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-rest-api#204]
**Describe the bug**
I am requested to input an organization ID when trying "GET /organizations" in the Swagger UI. This doesn't make sense. Please remove it.
 
**To Reproduce**
1. Login to /oscm-rest-api as supplier administrator.
2. Collapse the GET /organizations form for querying existing organizations.
3. Click try out
4. See the list of input parameters.

**Expected behavior**
Only version is required and offered for input.

**Observed behavior**
Beside of the version, ID, marketplaceID and organizationID is required.
I don't see any value in the latter three here. Remove them if not needed.

**Screenshots**
GET /organizations in the Swagger UI:

![image](https://user-images.githubusercontent.com/14805690/77452467-42e66800-6df6-11ea-95c2-b5f013189ccf.png)

**Additional context**
This similar case was found by verifying the fix of #184. Please check the list of endpoints if there are other occurrences of unneeded input parameters.

**Comment by kowalczyka** [comment]
This will be handled within #194
