### ISSUE TITLE
Update Organization Images

### ISSUE THREAD

**Issue by cworf91** [servicecatalog/oscm-rest-api#229]
**Summary**
Updating Services without images is possible. Now it should be also possible to update organization images.

**Details**
The REST API should provide an endpoint which allows to update images. Therefore the existing /put endpoint have to be extended.

**Acceptance criteria**
[ ] Images can be uploaded
[ ] Unit tests where implemented
[ ] Update organization without image still works

**Comment by GoebelL** [comment]
This is out of scope for now. Please reopen if you have a justified need.
