### ISSUE TITLE
Test access to marketpaces

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-rest-api#246]
**Summary**
Ensure restricted marketplaces can be accessed only by assigned users.

**Details**
Test service lists via Swagger UI if inaccessible services are correctly filtered.

**Acceptance criteria**
- [ ] API has been tested manually

**Comment by KabacinskiPiotr** [comment]
@GoebelL  Mostly it works fine.
But in the case of a reseller (broker), if his organization is not granted access to the restricted marketplace, it is still possible to assign a service to him as a reseller (broker). This service is displayed in the Swagger UI. The reseller (broker) still has no access to the restricted marketplace. 
Should we treat this behavior as a bug?

**Comment by GoebelL** [comment]
The described behavior is a bug. The get methods must not reveal service details that the connected user cannot access in the marketplace portal due to configured restrictions. I guess that the access check is missing in the backend implementation of the the service GET endpoint.

**Comment by GoebelL** [comment]
Maybe there is a misunderstanding. This might be invalid. I guess that UI and API don't behave differently here. If this is the case then this issue is void. 
The supplier can grant resell permissions to resellers and brokers for his services. This does not need to relate with the supplier marketplace. Even if the supplier marketplace is restricted for the reseller / broker organization the reseller / broker might still be able to publish the services on his own marketplace. Note that OSCM internally creates a copy of the supplier service for the reseller or broker if they are granted respective permissions that can be assigned to a different marketplace where they have access to.

@KabacinskiPiotr, can you confirm this?

**Comment by KabacinskiPiotr** [comment]
@GoebelL Yes you are right. The UI and API do not behave differently.
