### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-rest-api#250]
**Describe the bug**
This repo's readme contains a broken link for how to get started.

**To Reproduce**
Open the readme and click the `getting started` link at the end.

**Expected behavior**
Getting started documentation.

**Observed behavior**
HTTP 404

**Comment by KabacinskiPiotr** [comment]
Done https://github.com/servicecatalog/oscm-rest-api/commit/c2fe5877247dd9540f71387218660e14db4725ec
