### ISSUE TITLE
Remove oscm-commons 

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-rest-api#30]
Remove dependency to com.github.servicecatalog.oscm-commons. Check shared modules from oscm-commons and integrate those which are needed here.

Also, move oscm-rest-api-commons module to this repo

See https://github.com/servicecatalog/oscm-commons/issues/5

**Comment by adamczykba** [comment]
After discussion with @kowalczyka this task will be completed in scope of #6

**Comment by Crystalzord** [comment]
@adamczykba Please add test utility to the commons to remove redundancy in the unit tests (create parameters and uri info methods).
