### ISSUE TITLE
REST API modules deployment through Jenkins job

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-rest-api#45]
**Summary**
Right now, in order to deploy one of REST API module to *oscm-core* virtual machine it is necessary to perform all the steps manually.
REST API modules should be automatically built and deployed in scope of exsting Jenkins job

**Details**
N/A

**Acceptance criteria**
Following REST API modules are automatically deployable by Jenkins job:
~~- [x] oscm-rest-api-account~~
~~- [ ] oscm-rest-api-event~~
~~- [x] oscm-rest-api-identity~~
~~- [x] oscm-rest-api-marketplace~~
~~- [x] oscm-rest-api-operation~~
~~- [x] oscm-rest-api-service~~
~~- [ ] oscm-rest-api-subscription~~

*Following #90:*
- [ ] oscm-rest-api 

**Additional context**
N/A

**Comment by Crystalzord** [comment]
This can be already built using jenkins job with the following name: OSCM_Docker_build_and_push_REST_API
Although not all API's are ready yet.

**Comment by Crystalzord** [comment]
Completed in: https://github.com/servicecatalog/oscm-dockerbuild/pull/175#event-2488633041
and in the jenkinsScripts repository.
