### ISSUE TITLE
Add SonarQube support for oscm-rest-api

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-rest-api#53]
**Summary**
To ensure higher code quality let's introduce SonarQube support for this repository.

**Details**
TBD

**Acceptance criteria**
TBD

**Additional context**
- check wether it is fine to block the build on travis, when quality gate is not met

**Comment by KabacinskiPiotr** [comment]
@GoebelL,

Here is a sample report generated by [SonarCloud](https://sonarcloud.io/dashboard?id=org.heigit.ors%3Aopenrouteservice)

First, I'd like to add this functionality to the **oscm-approval** repository, and see how it performs. The report would only be available to the **master**.

**Comment by GoebelL** [comment]
Thanks. @KabacinskiPiotr 

>First, I'd like to add this functionality to the oscm-approval repository, and see how it performs.

Let's do this for the **oscm-rest-api** master branch fist. Just ping me on Slack when you have it there. Thanks.
