### ISSUE TITLE
Refactor/cleanup unit tests

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-rest-api#55]
**Summary**
In order for this repos unit tests to be consistent, let's recheck and improve the code whereever possible.

**Details**
N/A

**Acceptance criteria**
- [ ] overall code coverage is at least 70%
- [ ] unit tests for following modules are checked and refactored (if applicable)
- - [ ] oscm-rest-commons
- - [ ] oscm-rest-account
- - [ ] oscm-rest-identity
- - [ ] oscm-rest-marketplace
- - [ ] oscm-rest-operation
- - [ ] oscm-rest-service

**Additional context**
N/A

**Comment by Crystalzord** [comment]
Done in pull request: https://github.com/servicecatalog/oscm-rest-api/pull/61
