### ISSUE TITLE
Adapt Account REST API deployment for TomEE

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-rest-api#6]
**Summary**
After initial investigation, the single war package for account related API is deployable aliging module's web.xml configuration.

**Details**
org.oscm.rest.common.BasicAuthFilter does not exist in any of the project dependencies. It leads to problem with API deployment. After removing it deployment is possible, but the API is not working as there is no authentication provided - OSCM's EJBs which are used underneath require proper user roles. Such authentication filter must be reintroduced.

**Acceptance criteria**
- [x] OSCM ACCOUNT REST API war is deployable inside existing oscm-core container
- [x] it is possible to access API using BASIC authentication
- [x] endpoints functionality is verified

**Additional context**
N/A

**Comment by adamczykba** [comment]
@GoebelL 
It turned out that REST API modules will require some rework for them to work as expected.
It might be necessary to change some stuff in *oscm-rest-commons*, so I will proceed with #30 for now to avoid unnecessary mess

**Comment by GoebelL** [comment]
@adamczykba 

>It turned out that REST API modules will require some rework for them to work as expected.
>It might be necessary to change some stuff in oscm-rest-commons, so I will proceed with #30 for now >to avoid unnecessary mess

#30 is closed meanwhile, so I believe it's done. 
Thus, how about this issue?

**Comment by adamczykba** [comment]
@GoebelL 
Yes, #30 is already closed. Also this specific issue is already waiting for the review

**Comment by GoebelL** [comment]
Perfect.
