### ISSUE TITLE
Build latest on Jitpack 

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-rest-api#7]
For building on Jitpack find instructions on https://jitpack.io. This is very easy and useful for later integration with the OSCM Core build.

Generate snapshot build from master branch on this repo. 
Simply click this URL -> [https://jitpack.io/#servicecatalog/oscm-rest-api/master-SNAPSHOT](https://jitpack.io/#servicecatalog/oscm-rest-api/master-SNAPSHOT)
Add the snipet to the parent pom file of this multi module project.

Compare the settings with the configuration in [oscm-interfaces](https://github.com/servicecatalog/oscm-interfaces/).

**Comment by adamczykba** [comment]
@GoebelL 
Is this issue still valid?
Maybe we could provide some more details in the issue's description?
