### ISSUE TITLE
[Event] Swagger documentation

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-rest-api#75]
**Summary**
Swagger documentation should be provided for Event API endpoints

**Details**
N/A

**Acceptance criteria**
- [ ] Event API module has its own Swagger documentation
- [ ] Swagger version is updated to the latest one
- [ ] Mandatory parameters are documented

**Additional context**
- there are some swagger-related filed that can be used as a guideline (ex. account-service-rest-api.yaml)
- swagger documentation should be configured using Java annotations

**Comment by Crystalzord** [comment]
Done and merged to swagger branch. https://github.com/servicecatalog/oscm-rest-api/pull/110
