### ISSUE TITLE
[Identity] Swagger documentation

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-rest-api#76]
**Summary****Summary**
Swagger documentation should be provided for Identity API endpoints

**Details**
N/A

**Acceptance criteria**
- [ ] Identity API module has its own Swagger documentation
- [ ] Swagger version is updated to the latest one
- [ ] Mandatory parameters are documented

**Additional context**
- there are some swagger-related filed that can be used as a guideline (ex. account-service-rest-api.yaml)
- swagger documentation should be configured using Java annotations

Clear description or/and business justification of what the task is about.

**Details**
If applicable, detailed information regarding things to be considered, requirements etc.

**Acceptance criteria**
Precise and detailed conditions under which the task is considered to be completed.

**Additional context**
Add any other context or screenshots about the task.

**Comment by Crystalzord** [comment]
Done and merged to swagger branch
