### ISSUE TITLE
[Marketplace] Swagger documentation

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-rest-api#77]
**Summary**
Swagger documentation should be provided for Marketplace API endpoints

**Details**
N/A

**Acceptance criteria**
- [ ] Marketplace API module has its own Swagger documentation
- [ ] Swagger version is updated to the latest one
- [ ] Mandatory parameters are documented

**Additional context**
- there are some swagger-related filed that can be used as a guideline (ex. account-service-rest-api.yaml)
- swagger documentation should be configured using Java annotations

**Comment by Crystalzord** [comment]
Done on swagger branch
