### ISSUE TITLE
[Subscription] Improve error handling

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-rest-api#87]
**Summary**
Right now, error messages that are delivered though API request are not meaningful at all. 
We should review them and make it so end user actually knows what went wrong.

**Details**
N/A

**Acceptance criteria**
- [ ] error handling is reviewed
- [ ] error messages are more meningfull (no generic error messages!)
- [ ] proper error codes are used - 4xx for internal errors, 5xx for external errors

**Additional context**
N/A

**Comment by Crystalzord** [comment]
Please also add a handling for a situation, where GET is executed on a subscription with no usage licenses present. It results in NullPointException.
org.oscm.rest.subscription.UsageLicenseResource#getLicenses

**Comment by kowalczyka** [comment]
Closing as it will be handled within #219
