### ISSUE TITLE
Use ID from request URI instead of this from request body

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-rest-api#88]
**Summary**
Currently, most of the PUT endpoints require for user to put resource ID both in URI and request body. The first one is hovewer ignored in most cases. Let's change that behaviour.

**Details**
Application should use only ID from URI - the request one should be ignored.
It it possible that modification of some of the common REST classes will do the trick.

**Acceptance criteria**
- [ ] PUT endpoint uses only the ID from the URI
- [ ] Update Swagger documentation (i.e. PUT from /users/<username> endpoint)

**Additional context**
N/A

**Comment by Crystalzord** [comment]
Completed in two pull requests: #132 and #133
