### ISSUE TITLE
Test deploy oscm-rest-api-account.war

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-rest-api#9]
Task: 
* Test deployment of war file in tomee and investigate required adaption if any
* Test retrieving an existing organiztion: Build resource URL from yaml file (/organizations/{id}) and test access in the browser

**Comment by adamczykba** [comment]
@GoebelL 
In a past two days, I've investigated current state of this REST API project. These are the outomes so far:

- I've tired do deploy *account* part on *oscm-app* and *oscm-core* containers on my VM - neither of them works (Catalina is throwing errors during deployment step)
- I've tried to test it locally, by adding the endpoint that will return some sample, harcoded data - I was able to deploy on tomee in that case, but all request against my or any other provied endpoint resulted in 404
- project has no tests (unit nor integration) whatsoever
- POMs can be improved a bit
- travis configuration can be improved (right now it basically only executes the test phase)

My recommendation is to set up some meeting on date of Your preference, and talk through possible solutions and concepts
