### ISSUE TITLE
Implement TechnicalService#PUT endpoint

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm-rest-api#93]
**Summary**
PUT endpoint for TechnicalSerivce API is not implemented yet. Let's do something about that.

**Details**
Path to endpoint should be the following : **/technicalservices/{serviceId}**

**Acceptance criteria**
- [x] TechnicalSerivce#PUT endpoint is implemented
- [x] endpoint is fully operational
- [x] endpoint has proper Swagger documentation
- [x] Code Coverage on new code is at least 80%

**Additional context**
N/A

**Comment by kowalczyka** [comment]
PUT method will be used to import technical service.
